### PR TITLE
Fixed compile errors with ghc 8.10

### LINKED ISSUE #1: Data.Type.Functor.Product: Occurs check: cannot construct the infinite kind: as ~ a : as
Failing to build in Stackage Nightly with ghc-8.10.3

```
    [1 of 3] Compiling Data.Type.Functor.Product
    
    /var/stackage/work/unpack-dir/unpacked/functor-products-0.1.1.0-6c7d58498a2c23338baa8275a51e9099739812b1bd36126f887e5cdf57cce45b
/src/Data/Type/Functor/Product.hs:383:49: error:
        • Occurs check: cannot construct the infinite kind: as ~ a : as
        • In the third argument of ‘SIndex’, namely ‘('IS i)’
          In the type ‘SIndex (b : bs) a ('IS i)’
          In the definition of data constructor ‘SIS’
          NB: Type ‘SIndex’ was inferred to use visible dependent quantification.
          Most types with visible dependent quantification are
          polymorphically recursive and need a standalone kind
          signature. Perhaps supply one, with StandaloneKindSignatures.
        • Type variable kinds:
            a :: k0
            as :: [k0]
        |
    383 |     SIS :: SIndex bs a i -> SIndex (b ': bs) a ('IS i)
        |                                                 ^^^^^
```

### PR DESCRIPTION
**Pull request by xicesky**
This PR makes a few changes so functor-products compiles with ghc 8.10.
I didn't run any tests besides compiling the library, so please consider these changes ad-hoc.
This fixes mstksg/functor-products#1

Changes:

- Added kind signatures to various singletons, which were previously inferred to use visible dependent quantification
- Altered the "Disproved" case of indexRElem to avoid impredicative polymorphism.
   Otherwise, the resulting error would have type:
   `(RElem a as (V.RIndex a as) => r) -> r`

Tests:

- Checked that the source still compiles:
   - with ghc 8.8.4 (stackage lts-16.31)
   - with ghc 8.10.4 (stackage lts-17.4)

### CODE REVIEW

**Comment by mstksg** [comment]
Appreciate it, thank you very much!  Sorry I wasn't able to get to this in time :(
