### ISSUE TITLE
Data.Type.Functor.Product: Occurs check: cannot construct the infinite kind: as ~ a : as

### ISSUE THREAD

**Issue by juhp** [mstksg/functor-products#1]
Failing to build in Stackage Nightly with ghc-8.10.3

```
    [1 of 3] Compiling Data.Type.Functor.Product
    
    /var/stackage/work/unpack-dir/unpacked/functor-products-0.1.1.0-6c7d58498a2c23338baa8275a51e9099739812b1bd36126f887e5cdf57cce45b
/src/Data/Type/Functor/Product.hs:383:49: error:
        • Occurs check: cannot construct the infinite kind: as ~ a : as
        • In the third argument of ‘SIndex’, namely ‘('IS i)’
          In the type ‘SIndex (b : bs) a ('IS i)’
          In the definition of data constructor ‘SIS’
          NB: Type ‘SIndex’ was inferred to use visible dependent quantification.
          Most types with visible dependent quantification are
          polymorphically recursive and need a standalone kind
          signature. Perhaps supply one, with StandaloneKindSignatures.
        • Type variable kinds:
            a :: k0
            as :: [k0]
        |
    383 |     SIS :: SIndex bs a i -> SIndex (b ': bs) a ('IS i)
        |                                                 ^^^^^
```

**Comment by mstksg** [comment]
Should be resolved now, appreciate you bringing it up
